In [ ]:
##Import necessary modules

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pylab as plt 
%matplotlib inline 

In [2]:
df=pd.read_csv('AirlineF9.csv')

In [3]:
df=df.drop(columns=['Unnamed: 0'])
df

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK     FL_DATE CARRIER  \
0       2018        1      1             1            1  2018-01-01      F9   
1       2018        1      1             1            1  2018-01-01      F9   
2       2018        1      1             2            2  2018-01-02      F9   
3       2018        1      1             2            2  2018-01-02      F9   
4       2018        1      1             3            3  2018-01-03      F9   
...      ...      ...    ...           ...          ...         ...     ...   
183118  2019        2      6            26            3  2019-06-26      F9   
183119  2019        2      6            28            5  2019-06-28      F9   
183120  2019        2      6            29            6  2019-06-29      F9   
183121  2019        2      6            27            4  2019-06-27      F9   
183122  2019        2      6            30            7  2019-06-30      F9   

        FL_NUM  Route ORIGIN  ... NAS_DELAY SECURITY_DELAY  \
0          632     19    ABQ  ...       NaN            NaN   
1          630     19    ABQ  ...       NaN            NaN   
2          632     19    ABQ  ...       NaN            NaN   
3          630     19    ABQ  ...       NaN            NaN   
4          632     19    ABQ  ...       NaN            NaN   
...        ...    ...    ...  ...       ...            ...   
183118     587   6588    TYS  ...       NaN            NaN   
183119     587   6588    TYS  ...       NaN            NaN   
183120     587   6588    TYS  ...       NaN            NaN   
183121     219   6665    XNA  ...       6.0            0.0   
183122     219   6665    XNA  ...      99.0            0.0   

       LATE_AIRCRAFT_DELAY  PASSENGERS  EMPFULL  EMPPART  EMPTOTAL  EMPFTE  \
0                      NaN      3461.0   3706.0     39.0    3745.0  3726.0   
1                      NaN      3461.0   3706.0     39.0    3745.0  3726.0   
2                      NaN      3461.0   3706.0     39.0    3745.0  3726.0   
3                      NaN      3461.0   3706.0     39.0    3745.0  3726.0   
4                      NaN      3461.0   3706.0     39.0    3745.0  3726.0   
...                    ...         ...      ...      ...       ...     ...   
183118                 NaN      2940.0   4639.0     51.0    4690.0  4665.0   
183119                 NaN      2940.0   4639.0     51.0    4690.0  4665.0   
183120                 NaN      2940.0   4639.0     51.0    4690.0  4665.0   
183121                 0.0       308.0   4639.0     51.0    4690.0  4665.0   
183122                 0.0       308.0   4639.0     51.0    4690.0  4665.0   

        NET_INCOME OP_REVENUES  
0         24887.67   464436.41  
1         24887.67   464436.41  
2         24887.67   464436.41  
3         24887.67   464436.41  
4         24887.67   464436.41  
...            ...         ...  
183118    69809.24   593451.15  
183119    69809.24   593451.15  
183120    69809.24   593451.15  
183121    69809.24   593451.15  
183122    69809.24   593451.15  

[183123 rows x 50 columns]

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183123 entries, 0 to 183122
Data columns (total 50 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 183123 non-null  int64  
 1   QUARTER              183123 non-null  int64  
 2   MONTH                183123 non-null  int64  
 3   DAY_OF_MONTH         183123 non-null  int64  
 4   DAY_OF_WEEK          183123 non-null  int64  
 5   FL_DATE              183123 non-null  object 
 6   CARRIER              183123 non-null  object 
 7   FL_NUM               183123 non-null  int64  
 8   Route                183123 non-null  int64  
 9   ORIGIN               183123 non-null  object 
 10  DEST                 183123 non-null  object 
 11  DEST_CITY            183123 non-null  object 
 12  DEST_STATE           183123 non-null  object 
 13  CRS_DEP_TIME         183123 non-null  int64  
 14  DEP_TIME             179794 non-null  float64
 15  DEP_DELAY        

In [4]:
df.isna().sum()

YEAR                        0
QUARTER                     0
MONTH                       0
DAY_OF_MONTH                0
DAY_OF_WEEK                 0
FL_DATE                     0
CARRIER                     0
FL_NUM                      0
Route                       0
ORIGIN                      0
DEST                        0
DEST_CITY                   0
DEST_STATE                  0
CRS_DEP_TIME                0
DEP_TIME                 3329
DEP_DELAY                3399
DEP_DELAY_NEW            3399
DEP_DEL15                3399
DEP_DELAY_GROUP          3399
DEP_TIME_BLK                0
TAXI_OUT                 3508
WHEELS_OFF               3507
WHEELS_ON                3561
TAXI_IN                  3561
CRS_ARR_TIME                0
ARR_TIME                 3561
ARR_DELAY                3785
ARR_DELAY_NEW            3785
ARR_DEL15                3785
ARR_DELAY_GROUP          3785
ARR_TIME_BLK                0
CANCELED                    0
CANCELLATION_CODE      179615
DIVERTED  

In [5]:
df=df.dropna(subset=['ARR_DEL15'])

In [97]:
df['FL_NUM'].nunique()

1629

In [6]:
#binary encoding
import category_encoders as ce

encoder = ce.BinaryEncoder(cols=['CARRIER','ORIGIN','DEST','FL_NUM'])
df = encoder.fit_transform(df)

df.head()

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK     FL_DATE  CARRIER_0  \
0  2018        1      1             1            1  2018-01-01          1   
1  2018        1      1             1            1  2018-01-01          1   
2  2018        1      1             2            2  2018-01-02          1   
3  2018        1      1             2            2  2018-01-02          1   
4  2018        1      1             3            3  2018-01-03          1   

   FL_NUM_0  FL_NUM_1  FL_NUM_2  ...  NAS_DELAY  SECURITY_DELAY  \
0         0         0         0  ...        NaN             NaN   
1         0         0         0  ...        NaN             NaN   
2         0         0         0  ...        NaN             NaN   
3         0         0         0  ...        NaN             NaN   
4         0         0         0  ...        NaN             NaN   

   LATE_AIRCRAFT_DELAY  PASSENGERS  EMPFULL  EMPPART  EMPTOTAL  EMPFTE  \
0                  NaN      3461.0   3706.0     39.0    3745.0  3726.0   
1                  NaN      3461.0   3706.0     39.0    3745.0  3726.0   
2                  NaN      3461.0   3706.0     39.0    3745.0  3726.0   
3                  NaN      3461.0   3706.0     39.0    3745.0  3726.0   
4                  NaN      3461.0   3706.0     39.0    3745.0  3726.0   

   NET_INCOME  OP_REVENUES  
0    24887.67    464436.41  
1    24887.67    464436.41  
2    24887.67    464436.41  
3    24887.67    464436.41  
4    24887.67    464436.41  

[5 rows x 75 columns]

In [7]:
df.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE',
       'CARRIER_0', 'FL_NUM_0', 'FL_NUM_1', 'FL_NUM_2', 'FL_NUM_3', 'FL_NUM_4',
       'FL_NUM_5', 'FL_NUM_6', 'FL_NUM_7', 'FL_NUM_8', 'FL_NUM_9', 'FL_NUM_10',
       'FL_NUM_11', 'Route', 'ORIGIN_0', 'ORIGIN_1', 'ORIGIN_2', 'ORIGIN_3',
       'ORIGIN_4', 'ORIGIN_5', 'ORIGIN_6', 'ORIGIN_7', 'DEST_0', 'DEST_1',
       'DEST_2', 'DEST_3', 'DEST_4', 'DEST_5', 'DEST_6', 'DEST_7', 'DEST_CITY',
       'DEST_STATE', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW',
       'DEP_DEL15', 'DEP_DELAY_GROUP', 'DEP_TIME_BLK', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'ARR_DELAY_GROUP',
       'ARR_TIME_BLK', 'CANCELED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY',

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179338 entries, 0 to 183122
Data columns (total 75 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 179338 non-null  int64  
 1   QUARTER              179338 non-null  int64  
 2   MONTH                179338 non-null  int64  
 3   DAY_OF_MONTH         179338 non-null  int64  
 4   DAY_OF_WEEK          179338 non-null  int64  
 5   FL_DATE              179338 non-null  object 
 6   CARRIER_0            179338 non-null  int64  
 7   FL_NUM_0             179338 non-null  int64  
 8   FL_NUM_1             179338 non-null  int64  
 9   FL_NUM_2             179338 non-null  int64  
 10  FL_NUM_3             179338 non-null  int64  
 11  FL_NUM_4             179338 non-null  int64  
 12  FL_NUM_5             179338 non-null  int64  
 13  FL_NUM_6             179338 non-null  int64  
 14  FL_NUM_7             179338 non-null  int64  
 15  FL_NUM_8         

In [8]:
df['CRS_ARR_TIME'].values

array([ 700, 1904,  700, ..., 1252, 1842, 1812], dtype=int64)

In [13]:
df[['CARRIER_DELAY','LATE_AIRCRAFT_DELAY']].corr()

CARRIER_DELAY  LATE_AIRCRAFT_DELAY
CARRIER_DELAY             1.000000            -0.114067
LATE_AIRCRAFT_DELAY      -0.114067             1.000000

In [15]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

df.iloc[:,38] = labelencoder.fit_transform(df.iloc[:,38].values)
df.iloc[:,45] = labelencoder.fit_transform(df.iloc[:,45].values)
df.iloc[:,46] = labelencoder.fit_transform(df.iloc[:,46].values)
df.iloc[:,47] = labelencoder.fit_transform(df.iloc[:,47].values)
df.iloc[:,48] = labelencoder.fit_transform(df.iloc[:,48].values)
df.iloc[:,49] = labelencoder.fit_transform(df.iloc[:,49].values)

In [16]:
df=df.fillna(0)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 179338 entries, 0 to 183122
Data columns (total 75 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   YEAR                 179338 non-null  int64  
 1   QUARTER              179338 non-null  int64  
 2   MONTH                179338 non-null  int64  
 3   DAY_OF_MONTH         179338 non-null  int64  
 4   DAY_OF_WEEK          179338 non-null  int64  
 5   FL_DATE              179338 non-null  object 
 6   CARRIER_0            179338 non-null  int64  
 7   FL_NUM_0             179338 non-null  int64  
 8   FL_NUM_1             179338 non-null  int64  
 9   FL_NUM_2             179338 non-null  int64  
 10  FL_NUM_3             179338 non-null  int64  
 11  FL_NUM_4             179338 non-null  int64  
 12  FL_NUM_5             179338 non-null  int64  
 13  FL_NUM_6             179338 non-null  int64  
 14  FL_NUM_7             179338 non-null  int64  
 15  FL_NUM_8         

In [18]:
df.columns

Index(['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE',
       'CARRIER_0', 'FL_NUM_0', 'FL_NUM_1', 'FL_NUM_2', 'FL_NUM_3', 'FL_NUM_4',
       'FL_NUM_5', 'FL_NUM_6', 'FL_NUM_7', 'FL_NUM_8', 'FL_NUM_9', 'FL_NUM_10',
       'FL_NUM_11', 'Route', 'ORIGIN_0', 'ORIGIN_1', 'ORIGIN_2', 'ORIGIN_3',
       'ORIGIN_4', 'ORIGIN_5', 'ORIGIN_6', 'ORIGIN_7', 'DEST_0', 'DEST_1',
       'DEST_2', 'DEST_3', 'DEST_4', 'DEST_5', 'DEST_6', 'DEST_7', 'DEST_CITY',
       'DEST_STATE', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW',
       'DEP_DEL15', 'DEP_DELAY_GROUP', 'DEP_TIME_BLK', 'TAXI_OUT',
       'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME',
       'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'ARR_DELAY_GROUP',
       'ARR_TIME_BLK', 'CANCELED', 'CANCELLATION_CODE', 'DIVERTED',
       'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY',

In [27]:
# Use numpy to convert to arrays
import numpy as np

# Labels are the values we want to predict
labels = np.array(df['ARR_DELAY'])

# Remove the labels from the features
# axis 1 refers to the columns
features= df[[ 'YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK',
       'CARRIER_0', 'FL_NUM_0', 'FL_NUM_1', 'FL_NUM_2', 'FL_NUM_3', 'FL_NUM_4',
       'FL_NUM_5', 'FL_NUM_6', 'FL_NUM_7', 'FL_NUM_8', 'FL_NUM_9', 'FL_NUM_10',
       'FL_NUM_11','ORIGIN_0', 'ORIGIN_1', 'ORIGIN_2', 'ORIGIN_3',
       'ORIGIN_4', 'ORIGIN_5', 'ORIGIN_6', 'ORIGIN_7', 'DEST_0', 'DEST_1',
       'DEST_2', 'DEST_3', 'DEST_4', 'DEST_5', 'DEST_6', 'DEST_7','CRS_DEP_TIME',  'TAXI_OUT',
       'WHEELS_OFF','CRS_ARR_TIME', 'AIR_TIME', 'DISTANCE',
       'PASSENGERS', 'EMPTOTAL',
       'NET_INCOME', 'OP_REVENUES']]

# Saving feature names for later use
feature_list = list(features.columns)

# Convert to numpy array
features = np.array(features)

In [118]:
df['WHEELS_ON'].values

array([ 409, 1117,  402, ...,  739, 1155, 1180], dtype=int64)

In [119]:
feature_list

['YEAR',
 'QUARTER',
 'MONTH',
 'DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'CARRIER_0',
 'FL_NUM_0',
 'FL_NUM_1',
 'FL_NUM_2',
 'FL_NUM_3',
 'FL_NUM_4',
 'FL_NUM_5',
 'FL_NUM_6',
 'FL_NUM_7',
 'FL_NUM_8',
 'FL_NUM_9',
 'FL_NUM_10',
 'FL_NUM_11',
 'Route_0',
 'Route_1',
 'Route_2',
 'Route_3',
 'Route_4',
 'Route_5',
 'Route_6',
 'Route_7',
 'Route_8',
 'Route_9',
 'Route_10',
 'ORIGIN_0',
 'ORIGIN_1',
 'ORIGIN_2',
 'ORIGIN_3',
 'ORIGIN_4',
 'ORIGIN_5',
 'ORIGIN_6',
 'ORIGIN_7',
 'DEST_0',
 'DEST_1',
 'DEST_2',
 'DEST_3',
 'DEST_4',
 'DEST_5',
 'DEST_6',
 'DEST_7',
 'CRS_ARR_TIME',
 'DISTANCE',
 'PASSENGERS',
 'EMPFULL',
 'EMPPART',
 'EMPTOTAL',
 'EMPFTE',
 'NET_INCOME',
 'OP_REVENUES',
 'AIR_TIME']

In [11]:
labels

array([ -2., -18.,  -9., ..., -25.,  44.,  99.])

In [28]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import KFold
import pandas as pd
from sklearn import metrics

In [29]:
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2)

In [30]:
import time
from sklearn.ensemble import RandomForestRegressor
start = time.time()
# Instantiate model 
rf_reg = RandomForestRegressor(n_estimators=30)
rf_reg.fit(x_train,y_train)

end = time.time()
print(f"{end-start} seconds")

288.2900221347809 seconds


In [31]:
y_pred = rf_reg.predict(x_test)

rsqure_score = rf_reg.score(x_train,y_train)
print('R^2: {}'.format(rsqure_score))
rsqure_testscore = rf_reg.score(x_test,y_test)
print('R^2: {}'.format(rsqure_testscore))

R^2: 0.9915378524766684
R^2: 0.9462043237936563


In [32]:
# Get numerical feature importances
importances = list(rf_reg.feature_importances_)

# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 5)) for feature, importance in zip(feature_list, importances)]

# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)

# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: CRS_DEP_TIME         Importance: 0.58884
Variable: WHEELS_OFF           Importance: 0.30691
Variable: TAXI_OUT             Importance: 0.03463
Variable: CRS_ARR_TIME         Importance: 0.01861
Variable: AIR_TIME             Importance: 0.01366
Variable: DAY_OF_MONTH         Importance: 0.00476
Variable: DISTANCE             Importance: 0.00463
Variable: PASSENGERS           Importance: 0.00455
Variable: Route                Importance: 0.00352
Variable: EMPTOTAL             Importance: 0.00263
Variable: DAY_OF_WEEK          Importance: 0.00237
Variable: MONTH                Importance: 0.00229
Variable: NET_INCOME           Importance: 0.00075
Variable: OP_REVENUES          Importance: 0.00072
Variable: FL_NUM_11            Importance: 0.0006
Variable: FL_NUM_4             Importance: 0.00059
Variable: FL_NUM_1             Importance: 0.00056
Variable: FL_NUM_7             Importance: 0.00055
Variable: FL_NUM_3             Importance: 0.00053
Variable: DEST_7               I

# Perform the training using K Fold cross validation method

In [33]:
cv_r2_scores_rf = cross_val_score(rf_reg, features, labels, cv=5,scoring='r2')
print(cv_r2_scores_rf)
print("Mean 5-Fold R Squared: {}".format(np.mean(cv_r2_scores_rf)))

[0.91404375 0.9400968  0.94395323 0.89210975 0.92070549]
Mean 5-Fold R Squared: 0.9221818043170353


In [36]:
# Use the forest's predict method on the test data
predictions = rf_reg.predict(x_test)

# Calculate the absolute errors
errors = abs(predictions - y_test)

# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 8.11 degrees.


In [137]:
df['FL_NUM_6']

0         0
1         0
2         0
3         0
4         0
         ..
183118    0
183119    0
183120    0
183121    0
183122    0
Name: FL_NUM_6, Length: 179338, dtype: int64

In [139]:
df[['PASSENGERS','ARR_DELAY']].corr()

PASSENGERS  ARR_DELAY
PASSENGERS    1.000000   0.008391
ARR_DELAY     0.008391   1.000000